name: water-project

services:
  db:
    image: postgres:16
    container_name: water_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: water_user
      POSTGRES_PASSWORD: water_pass
      POSTGRES_DB: water_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: