"""add farm dimensions

Revision ID: 139393993847
Revises: 617732675742
Create Date: 2026-05-03 21:33:48.611699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '139393993847'
down_revision: Union[str, Sequence[str], None] = '617732675742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('farm_width_m', sa.Float(), nullable=False))
    op.add_column('farms', sa.Column('farm_height_m', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'farm_height_m')
    op.drop_column('farms', 'farm_width_m')
    # ### end Alembic commands ###
