"""add simulation metadata fields

Revision ID: 5557a8eae5e9
Revises: 6fcd839d5df4
Create Date: 2026-05-05 21:15:45.409928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5557a8eae5e9'
down_revision: Union[str, Sequence[str], None] = '6fcd839d5df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('simulations', sa.Column('tank_current_l', sa.Float(), nullable=False))
    op.add_column('simulations', sa.Column('n_weeks', sa.Integer(), nullable=False))
    op.alter_column('simulations', 'farm_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('simulations', 'simulation_type',
               existing_type=postgresql.ENUM('optimized', 'naive', name='simulationtype'),
               nullable=True)
    op.drop_index(op.f('ix_simulations_id'), table_name='simulations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_simulations_id'), 'simulations', ['id'], unique=False)
    op.alter_column('simulations', 'simulation_type',
               existing_type=postgresql.ENUM('optimized', 'naive', name='simulationtype'),
               nullable=False)
    op.alter_column('simulations', 'farm_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('simulations', 'n_weeks')
    op.drop_column('simulations', 'tank_current_l')
    op.drop_column('simulations', 'start_date')
    # ### end Alembic commands ###
