"""add parcels table, remove area_m2 from farm_crops

Revision ID: 6fcd839d5df4
Revises: 139393993847
Create Date: 2026-05-04 00:08:49.761256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fcd839d5df4'
down_revision: Union[str, Sequence[str], None] = '139393993847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm_crops', 'area_m2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm_crops', sa.Column('area_m2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
