"""initial schema

Revision ID: 842f1f336816
Revises: 
Create Date: 2026-03-21 23:10:41.093579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842f1f336816'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_perennial', sa.Boolean(), nullable=True),
    sa.Column('stage_initial_weeks', sa.Integer(), nullable=True),
    sa.Column('stage_dev_weeks', sa.Integer(), nullable=True),
    sa.Column('stage_mid_weeks', sa.Integer(), nullable=True),
    sa.Column('stage_late_weeks', sa.Integer(), nullable=True),
    sa.Column('kc_initial', sa.Float(), nullable=False),
    sa.Column('kc_mid', sa.Float(), nullable=False),
    sa.Column('kc_late', sa.Float(), nullable=False),
    sa.Column('min_water_mm_week', sa.Float(), nullable=False),
    sa.Column('drought_tolerance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crops_id'), 'crops', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('municipality', sa.String(), nullable=False),
    sa.Column('tank_capacity', sa.Float(), nullable=False),
    sa.Column('tank_current_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_id'), 'farms', ['id'], unique=False)
    op.create_table('farm_crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('area_m2', sa.Float(), nullable=False),
    sa.Column('planting_date', sa.Date(), nullable=True),
    sa.Column('current_stage', sa.Enum('initial', 'mid', 'late', name='perennialstage'), nullable=True),
    sa.Column('is_harvested', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_crops_id'), 'farm_crops', ['id'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('simulation_type', sa.Enum('optimized', 'naive', name='simulationtype'), nullable=False),
    sa.Column('priority', sa.Enum('sensitive', 'equal', 'economic', name='priority'), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_id'), 'simulations', ['id'], unique=False)
    op.create_table('simulation_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('farm_crop_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('allocated_l', sa.Float(), nullable=False),
    sa.Column('demanded_l', sa.Float(), nullable=False),
    sa.Column('tank_level_l', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['farm_crop_id'], ['farm_crops.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_weeks_id'), 'simulation_weeks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_weeks_id'), table_name='simulation_weeks')
    op.drop_table('simulation_weeks')
    op.drop_index(op.f('ix_simulations_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_farm_crops_id'), table_name='farm_crops')
    op.drop_table('farm_crops')
    op.drop_index(op.f('ix_farms_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_crops_id'), table_name='crops')
    op.drop_table('crops')
    # ### end Alembic commands ###
