"""add municipalities table, farm references municipality

Revision ID: a3e3678b9ac7
Revises: f97d2ed246fd
Create Date: 2026-03-23 23:07:02.925108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3e3678b9ac7'
down_revision: Union[str, Sequence[str], None] = 'f97d2ed246fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
