"""add municipalities table, farm references municipality

Revision ID: cbed86a72154
Revises: 842f1f336816
Create Date: 2026-03-23 23:03:00.331105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbed86a72154'
down_revision: Union[str, Sequence[str], None] = '842f1f336816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude_m', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_municipalities_id'), 'municipalities', ['id'], unique=False)
    op.add_column('farms', sa.Column('municipality_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'farms', 'municipalities', ['municipality_id'], ['id'])
    op.drop_column('farms', 'municipality')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('municipality', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'farms', type_='foreignkey')
    op.drop_column('farms', 'municipality_id')
    op.drop_index(op.f('ix_municipalities_id'), table_name='municipalities')
    op.drop_table('municipalities')
    # ### end Alembic commands ###
