"""move the tank capacity to simulation

Revision ID: eab5dda0353f
Revises: a3e3678b9ac7
Create Date: 2026-04-04 17:54:40.937804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab5dda0353f'
down_revision: Union[str, Sequence[str], None] = 'a3e3678b9ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'tank_current_pct')
    op.add_column('simulations', sa.Column('tank_current_pct', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'tank_current_pct')
    op.add_column('farms', sa.Column('tank_current_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
